In [22]:
import pandas as ps
import numpy as nm
import matplotlib.pyplot as plt

In [23]:
#importing data:

df = ps.read_csv("../data/bestsellers with categories.csv")
df.head()

#to import excel file
# df = pd.read_excel(<Filepath>)

#for particular sheet:
# df = pd.read_excel(<filepath>, sheet_name = "<name>")


# last 5 record: df.tail()
# for first 5: df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [24]:
df = ps.read_csv("../data/Data.csv")
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [25]:
# to know columns:
# dataset.columns


#to find datatype of columns:
# dataset.dtypes


#to find info of dataset:       --- it going to show METADATA for our dataset.
# dataset.info() 


#it describe everything about dataset
# dataset.describe()


#to find NULL in my dataset:
#dataset.isnull().sum()             -- sum() show total null in dataset.


#to check duplicate:
# dataset.duplicated().sum()

In [26]:
# we have 2 kind of variable: 1. Indepenent var and 2. Dependent var.
# we do: Column split for it then ROW split.


#split independent variable
#loc uses labels
# iloc uses integer position (number from 0 to the length of the data) 

print("InDependent variable, X:")
x = df.iloc[:, :-1].values                  #[:, :-1] --- all column; not last one
print(x)

print("Dependent variable, Y:")
y = df.iloc[:, 3 ].values
print(y)

InDependent variable, X:
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Dependent variable, Y:
<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

In [27]:
#taking care of missing data

from sklearn.impute import SimpleImputer

impute = SimpleImputer(missing_values=nm.nan, strategy='mean')
impute = impute.fit(x[:, 1:3])                      #fit: is going to perform operation on dataset of terms we give to it.

x[:, 1:3] = impute.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [28]:
#Encoding categorial data
#Encoding the Indpendent variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:,0])

print(x)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]

In [35]:
#Split data into Training and Test data

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=45)      #test_size = 0.2 --- it take 80% data for trainig and other 20% for testing

print("Train: ", x_train, "\n\n\nTest:", x_test,"\n\n\nY Train: ", y_train, "\n\n\nY Test:", y_test)

Train:  [[2 27.0 48000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]
 [2 38.77777777777778 52000.0]
 [0 35.0 58000.0]
 [0 48.0 79000.0]
 [0 44.0 72000.0]
 [2 38.0 61000.0]]


Test: [[1 30.0 54000.0]
 [1 40.0 63777.77777777778]]


Y Train:  <StringArray>
['Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No']
Length: 8, dtype: str


Y Test: <StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [ ]:
#Feature scaling 
#sc_X = (X[1]-mean) / Standard deavition
#For classification we are going to use Scaling or StandardScaler.
#For regression we are not going to use StandardScaler.

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)               #fit_transform --- its going to 'learn'
x_test = sc_x.transform(x_test)


print("Train: ",x_train,"\n\n\nTest: ",x_test)

Train:  [[ 1.21355975 -1.82709535 -1.45240802]
 [ 0.13483997  1.47603773  1.53784378]
 [-0.94387981 -0.39095053  0.17087153]
 [ 1.21355975 -0.1356359  -1.11066496]
 [-0.94387981 -0.6781795  -0.59805036]
 [-0.94387981  1.18880877  1.19610072]
 [-0.94387981  0.61435084  0.59805036]
 [ 1.21355975 -0.24733605 -0.34174306]]


Test:  [[1.00000000e+00 3.00000000e+01 5.40000000e+04]
 [1.00000000e+00 4.00000000e+01 6.37777778e+04]]