In [45]:
# # work on other do dataset
# bestseller
# Groceris

In [46]:
import pandas as ps
import numpy as nm
import matplotlib.pyplot as plt

In [47]:
#importing data:

df = ps.read_csv("../data/bestsellers.csv")
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  548 non-null    float64
 3   Reviews      549 non-null    float64
 4   Price        549 non-null    float64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(3), int64(1), str(3)
memory usage: 30.2 KB

In [49]:
df.isnull().sum()

# null_rows = df[df.isnull().all(axis=1)]
# print(null_rows)

Name           0
Author         0
User Rating    2
Reviews        1
Price          1
Year           0
Genre          0
dtype: int64

In [50]:
df.fillna({
    'User Rating': df['User Rating'].mean(),
    'Reviews': df['Reviews'].mean(),
    'Price': df['Price'].mean()
}, inplace=True)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2019,Non Fiction

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    float64
 4   Price        550 non-null    float64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(3), int64(1), str(3)
memory usage: 30.2 KB

In [52]:
print("Duplicate Values: ", df.duplicated().sum())

Duplicate Values:  0