<h1> Task: do ridge vs multiple on dataset and compare.</h1>

Task: 1. Predict final score for a new student who studies 7 hrs and attend 5 classes
<br>
2. To OLS on this data

In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [3]:
data = {
    'HRS_STU' : [2,4,6,8,10],
    'CLS_ATT' : [3,4,5,6,8],
    'FLS_SCR' : [65,70,75,85,95]
}

df = pd.DataFrame(data)

df

   HRS_STU  CLS_ATT  FLS_SCR
0        2        3       65
1        4        4       70
2        6        5       75
3        8        6       85
4       10        8       95

In [4]:
x = df[[
    "HRS_STU",
    "CLS_ATT"
]]

x

   HRS_STU  CLS_ATT
0        2        3
1        4        4
2        6        5
3        8        6
4       10        8

In [5]:
y = df[[
    "FLS_SCR"
]]

y

   FLS_SCR
0       65
1       70
2       75
3       85
4       95

In [13]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=45
)

model = LinearRegression()
model.fit(x, y)

ypred = model.predict(xtest)

ypred

array([[70.5]])

In [ ]:
print("Intercept: ", model.intercept_)

Intercept:  [47.5]

In [18]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(ytest,ypred)
mse = mean_squared_error(ytest,ypred)
rmse = np.sqrt(mse)
r2 = r2_score(ytest,ypred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score: ", r2)

MAE: 0.5
MSE: 0.25
RMSE: 0.5
R2 Score:  nan

c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)