In [42]:
# 1. before converting data into ridge regression, we have to do StandardScalar first

# #Create pipeline:

# 1. Standardize the predicitons
# 2. 





import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [43]:
data = {
    "Study_hour": [2,3,4,5,6,7,8,9],
    "aten" : [60,65,70,75,80,85,90,95],
    "ass_sc" : [50,55,58,65,70,74,80,88],
    "final_mark" : [42,48,54,61,67,73,81,89]
}

df = pd.DataFrame(data)

x = df.iloc[:,0:3]
y = df["final_mark"]

In [44]:
x

   Study_hour  aten  ass_sc
0           2    60      50
1           3    65      55
2           4    70      58
3           5    75      65
4           6    80      70
5           7    85      74
6           8    90      80
7           9    95      88

In [45]:
y

0    42
1    48
2    54
3    61
4    67
5    73
6    81
7    89
Name: final_mark, dtype: int64

In [46]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)             # ---- X is our independen varibale

In [47]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [48]:
model = make_pipeline(
    StandardScaler(),
    Ridge(alpha=1.0)
)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([49.09249889, 73.46107412])

In [49]:
from sklearn.linear_model import RidgeCV

model = RidgeCV(
    alphas= [0.01, 0.1, 1, 10,100],
    cv = 5
)

model.fit(x_train, y_train)

print("Best Alphas: ", model.alpha_)

Best Alphas:  0.01

c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_regression.py:1295: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(

In [50]:
model = make_pipeline(
    StandardScaler(),
    RidgeCV(alphas= [0.01, 0.1, 1, 10,100])
)

model.fit(x_train, y_train)

Ridge_model = model.named_steps["ridgecv"]

print("Best Alphas: ", Ridge_model.alpha_)

Best Alphas:  0.1

<h1>Lasso Implementation</h1>

In [51]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [52]:
data = {
    "SH" : [1,2,2,3,3,4,5,5,6,7,7,8,8,9,10],
    "ATT" : [55,60,6,62,70,72,75,80,78,82,85,88,90,92,95],
    "ASS_SCR" :[40,45,50,48,55,58,62,67,65,70,74,78,80,85,90],
    "STU_ID" : [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115],
    "Fi_Ma" : [35,40,43,45,50,54,60,64,66,71,74,79,82,87,92]
}

df = pd.DataFrame(data)

df

    SH  ATT  ASS_SCR  STU_ID  Fi_Ma
0    1   55       40     101     35
1    2   60       45     102     40
2    2    6       50     103     43
3    3   62       48     104     45
4    3   70       55     105     50
5    4   72       58     106     54
6    5   75       62     107     60
7    5   80       67     108     64
8    6   78       65     109     66
9    7   82       70     110     71
10   7   85       74     111     74
11   8   88       78     112     79
12   8   90       80     113     82
13   9   92       85     114     87
14  10   95       90     115     92

In [53]:
x = df[
    [
        "SH",
        "ATT",
        "ASS_SCR",
        "STU_ID"
    ]
]
y  = df ["Fi_Ma"]
x

    SH  ATT  ASS_SCR  STU_ID
0    1   55       40     101
1    2   60       45     102
2    2    6       50     103
3    3   62       48     104
4    3   70       55     105
5    4   72       58     106
6    5   75       62     107
7    5   80       67     108
8    6   78       65     109
9    7   82       70     110
10   7   85       74     111
11   8   88       78     112
12   8   90       80     113
13   9   92       85     114
14  10   95       90     115

In [54]:
y

0     35
1     40
2     43
3     45
4     50
5     54
6     60
7     64
8     66
9     71
10    74
11    79
12    82
13    87
14    92
Name: Fi_Ma, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = make_pipeline(
    StandardScaler(),
    Lasso(alpha=0.1)
)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

lasso_model = model.named_steps["lasso"]

coefficient_table = pd.DataFrame({
    "Predicitor" : x.columns,
    "Lasso Coefficient" : lasso_model.coef_
})

print(coefficient_table)